### ISSUE TITLE
* 

### ISSUE THREAD

**Issue by Stefan-Espant** [jtoufik/connect-your-tribe-profile-card#4]
Momenteel heeft je website nog een standaard margin.
Deze kan je eenvoudig oplossen dmv css

```css
* {
box-sizing: border-box;
margin: 0;
padding: 0;
}

```
